'use client';
import { useState } from 'react';
import { AnimatePresence, motion, useScroll, useTransform } from 'framer-motion';
import { ArrowUpRight, X } from 'lucide-react';

const projects=[
  {name:'HALO / AI OPERATING LAYER',kind:'AI PRODUCT',year:'2026',tone:'bg-[#111111] text-white',copy:'An adaptive operating layer translating enterprise signals into decisions, workflows and action.'},
  {name:'NOMA / FUTURE COMMERCE',kind:'DIGITAL EXPERIENCE',year:'2026',tone:'bg-[#D9D5CE] text-black',copy:'A spatial commerce environment built around editorial motion, product ritual and seamless interaction.'},
  {name:'VERGE / BRAND SYSTEM',kind:'BRAND INTELLIGENCE',year:'2025',tone:'bg-[#C7FF2F] text-black',copy:'A living identity system designed to scale from campaign language to product interface.'}
];
function Card({project,index,onOpen}:{project:(typeof projects)[number];index:number;onOpen:()=>void}){const {scrollYProgress}=useScroll();const scale=useTransform(scrollYProgress,[0,1],[1,0.96-index*.01]);return <motion.article style={{scale,top:80+index*18}} className={`sticky min-h-[78vh] rounded-[2px] overflow-hidden p-6 md:p-10 mb-8 ${project.tone}`}><div className="flex justify-between text-[10px] tracking-[.25em]"><span>{project.kind}</span><span>{project.year}</span></div><div className="absolute inset-0 halftone opacity-15"/><div className="relative z-10 h-full min-h-[68vh] flex flex-col justify-end"><h3 className="text-[11vw] md:text-[7vw] leading-[.82] tracking-[-.07em] max-w-5xl">{project.name}</h3><button onClick={onOpen} className="mt-8 w-max flex items-center gap-3 text-xs tracking-[.18em] border-b border-current pb-2">VIEW CASE <ArrowUpRight size={15}/></button></div></motion.article>}
export default function FeaturedWork(){const [open,setOpen]=useState<number|null>(null);return <section id="work" className="section-line px-5 md:px-8 py-24 md:py-32"><div className="flex justify-between mb-12"><p className="text-[10px] uppercase tracking-[.32em] text-muted">02 / SELECTED WORK</p><span className="text-[10px] tracking-[.2em]">SCROLL / STACK</span></div>{projects.map((p,i)=><Card key={p.name} project={p} index={i} onOpen={()=>setOpen(i)}/>)}<AnimatePresence>{open!==null&&<motion.div initial={{y:'100%'}} animate={{y:0}} exit={{y:'100%'}} transition={{duration:.7,ease:[.22,1,.36,1]}} className="fixed inset-0 z-[80] bg-foreground text-background p-6 md:p-12 overflow-y-auto"><button className="fixed right-6 top-6 md:right-10 md:top-10" onClick={()=>setOpen(null)}><X size={30}/></button><div className="min-h-screen flex flex-col justify-center max-w-6xl"><p className="text-xs tracking-[.25em] text-background/55">CASE STUDY / {projects[open].year}</p><h3 className="mt-6 text-[13vw] md:text-[8vw] leading-[.82] tracking-[-.07em]">{projects[open].name}</h3><p className="mt-10 max-w-2xl text-lg md:text-2xl text-background/65 leading-relaxed">{projects[open].copy}</p></div></motion.div>}</AnimatePresence></section>}