'use client';
import {AnimatePresence,motion,useScroll,useTransform} from 'framer-motion';
import {MoveUpRight,X} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';

type Project={title:string;kind:string;year:string;video:string;summary:string;detail:string};
const projects:Project[]=[
 {title:'ORBIT',kind:'AI OPERATING SYSTEM',year:'2026',video:'/softwarepar-portfolio/assets/Create_a_cinematic_hero_video.mp4',summary:'An intelligent operating layer for high-velocity teams.',detail:'ORBIT unifies signal, workflow and decision support into one adaptive interface. The concept explores how AI can become an ambient operating system rather than another dashboard.'},
 {title:'NEURAL',kind:'PREDICTIVE COMMERCE',year:'2026',video:'/softwarepar-portfolio/assets/Create_a_sophisticated_cinemat.mp4',summary:'A predictive commerce system that turns behavior into action.',detail:'NEURAL combines real-time intent modeling, automated segmentation and responsive merchandising to demonstrate a future-facing commerce experience.'},
 {title:'VECTOR',kind:'DIGITAL INFRASTRUCTURE',year:'2026',video:'/softwarepar-portfolio/assets/Create_an_extreme_macro_cinema.mp4',summary:'A modular command surface for distributed digital operations.',detail:'VECTOR reframes infrastructure software as a premium product experience: precise, calm and fast, with progressive disclosure for complex operational data.'},
];

function ProjectVideo({src,title}:{src:string;title:string}){return <video aria-label={title} autoPlay muted loop playsInline preload="metadata" className="absolute inset-0 h-full w-full object-cover"><source src={src} type="video/mp4"/></video>}

function ProjectCard({project,index,onOpen}:{project:Project;index:number;onOpen:()=>void}){const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start start','end start']});const scale=useTransform(scrollYProgress,[0,1],[1,.94]);return <div ref={ref} className="sticky top-20 min-h-[82vh] py-4" style={{zIndex:index+1}}><motion.article style={{scale}} className="relative mx-auto h-[78vh] min-h-[560px] max-w-[1500px] overflow-hidden rounded-[2rem] bg-black text-white shadow-[0_35px_100px_rgba(0,0,0,.18)]"><ProjectVideo src={project.video} title={`${project.title} cinematic case study`}/><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/90 via-black/5 to-black/20"/><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_center,transparent_25%,rgba(0,0,0,.18)_100%)]"/><div className="absolute inset-x-0 bottom-0 grid gap-6 p-7 md:grid-cols-[1fr_auto] md:items-end md:p-12"><div><p className="label mb-4 text-white/65">0{index+1} / {project.kind} / {project.year}</p><h3 className="text-[15vw] font-medium leading-[.76] tracking-[-.075em] md:text-[9vw]">{project.title}</h3><p className="mt-5 max-w-xl text-base text-white/80 md:text-lg">{project.summary}</p></div><button onClick={onOpen} className="group flex w-max items-center gap-5 rounded-full border border-white/40 bg-black/20 px-6 py-3 text-xs tracking-[.18em] backdrop-blur-md">VIEW CASE <MoveUpRight size={15} className="transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1"/></button></div></motion.article></div>}

export default function FeaturedWork(){const [active,setActive]=useState<Project|null>(null);useEffect(()=>{document.body.style.overflow=active?'hidden':'';return()=>{document.body.style.overflow=''}},[active]);return <section id="work" className="section-line bg-secondary px-5 py-28 md:px-8 md:py-36"><div className="mx-auto max-w-[1600px]"><div className="mb-16 flex items-end justify-between"><div><p className="label mb-5 text-muted">SELECTED WORK / 02</p><h2 className="text-6xl font-medium tracking-[-.06em] md:text-8xl">Work with gravity.</h2></div><p className="hidden max-w-sm text-sm leading-6 text-muted md:block">Three speculative systems built as complete product stories, not decorative mockups.</p></div>{projects.map((p,i)=><ProjectCard key={p.title} project={p} index={i} onOpen={()=>setActive(p)}/>)}</div><AnimatePresence>{active&&<motion.div initial={{y:'100%'}} animate={{y:0}} exit={{y:'100%'}} transition={{duration:.7,ease:[.16,1,.3,1]}} className="fixed inset-0 z-[120] overflow-y-auto bg-[#0A0A0A] text-white"><button onClick={()=>setActive(null)} className="fixed right-5 top-5 z-10 rounded-full border border-white/20 bg-white/10 p-3 backdrop-blur-md md:right-8 md:top-8"><X size={22}/></button><div className="mx-auto grid min-h-screen max-w-[1600px] items-center gap-10 px-5 py-24 md:grid-cols-2 md:px-8"><div className="relative aspect-video overflow-hidden rounded-3xl bg-black"><ProjectVideo src={active.video} title={`${active.title} case study motion`}/><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/25 to-transparent"/></div><div><p className="label text-white/50">CASE STUDY / {active.kind}</p><h3 className="mt-5 text-[18vw] font-medium leading-[.78] tracking-[-.075em] md:text-[8vw]">{active.title}</h3><p className="mt-8 max-w-2xl text-xl leading-8 text-white/70">{active.detail}</p><div className="mt-12 grid grid-cols-2 gap-6 border-t border-white/20 pt-6 text-sm"><div><p className="label mb-2 text-white/40">ROLE</p><p>Strategy / UX / AI / Motion</p></div><div><p className="label mb-2 text-white/40">YEAR</p><p>{active.year}</p></div></div></div></div></motion.div>}</AnimatePresence></section>}
