'use client';
import {useEffect,useState} from 'react';
import {AnimatePresence,motion,useScroll,useTransform} from 'framer-motion';
import {ArrowUpRight,X} from 'lucide-react';
const projects=[
 {name:'NEURAL FIELD',type:'AI PLATFORM / 2026',copy:'An adaptive intelligence layer for complex operational decisions.',image:'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=1800&q=90',tone:'bg-[#101010] text-white'},
 {name:'MONOFORM',type:'FASHION SYSTEM / 2026',copy:'A spatial commerce experience built around editorial rhythm and motion.',image:'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1800&q=90',tone:'bg-[#d8d3c8] text-black'},
 {name:'VECTOR',type:'MOBILITY / 2026',copy:'A high-performance product launch told through speed, scale and silence.',image:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1800&q=90',tone:'bg-[#d8ff32] text-black'}
];
function WorkCard({project,index,onOpen}:{project:(typeof projects)[number];index:number;onOpen:()=>void}){const {scrollYProgress}=useScroll();const scale=useTransform(scrollYProgress,[0,1],[1,Math.max(.9,1-index*.025)]);return <motion.article style={{scale,top:80+index*18}} className={`sticky mb-8 min-h-[76vh] overflow-hidden rounded-[2rem] ${project.tone} card-shadow`}><div className="grid min-h-[76vh] grid-cols-12"><div className="col-span-12 flex flex-col justify-between p-6 md:col-span-5 md:p-10"><div className="flex justify-between"><span className="label opacity-60">PROJECT / 0{index+1}</span><span className="label opacity-60">{project.type}</span></div><div><h3 className="display text-[14vw] font-medium md:text-[5.6vw]">{project.name}</h3><p className="mt-7 max-w-sm text-sm leading-6 opacity-70 md:text-base">{project.copy}</p><button onClick={onOpen} className="group mt-8 flex items-center gap-3 rounded-full border border-current px-5 py-3 text-xs tracking-[.16em]">VIEW CASE <ArrowUpRight size={15} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></button></div></div><div className="relative col-span-12 min-h-[46vh] overflow-hidden md:col-span-7 md:min-h-full"><img src={project.image} alt="" className="absolute inset-0 h-full w-full object-cover transition-transform duration-1000 hover:scale-105"/><div className="absolute inset-0 bg-black/10"/></div></div></motion.article>}
export default function FeaturedWork(){const [open,setOpen]=useState<number|null>(null);useEffect(()=>{document.body.style.overflow=open===null?'':'hidden';return()=>{document.body.style.overflow=''}},[open]);return <section id="work" className="section-line px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1600px]"><div className="mb-16 flex items-end justify-between"><div><span className="label text-muted">SELECTED WORK / 02</span><h2 className="display mt-5 text-[16vw] font-medium md:text-[8vw]">BUILT TO<br/>BE <span className="italic font-normal">FELT.</span></h2></div><span className="label hidden text-muted md:block">03 PROJECTS / SCROLL ↓</span></div>{projects.map((p,i)=><WorkCard key={p.name} project={p} index={i} onOpen={()=>setOpen(i)}/>)}</div><AnimatePresence>{open!==null&&<motion.div initial={{y:'100%'}} animate={{y:0}} exit={{y:'100%'}} transition={{duration:.7,ease:[.22,1,.36,1]}} className="fixed inset-0 z-[80] overflow-y-auto bg-[#0a0a0a] text-white"><button onClick={()=>setOpen(null)} className="fixed right-6 top-6 z-10 rounded-full border border-white/30 p-3 backdrop-blur-md"><X/></button><div className="mx-auto grid min-h-screen max-w-[1600px] grid-cols-12 gap-6 px-5 py-24 md:px-8"><div className="col-span-12 md:col-span-5"><span className="label text-white/50">CASE STUDY / 0{open+1}</span><h3 className="display mt-6 text-[16vw] md:text-[7vw]">{projects[open].name}</h3><p className="mt-8 max-w-md text-lg leading-8 text-white/60">{projects[open].copy} Strategy, interaction and interface were shaped as one continuous system — from first impression to final action.</p></div><div className="col-span-12 md:col-span-7"><img src={projects[open].image} alt="" className="h-[70vh] w-full object-cover"/><div className="mt-8 grid grid-cols-3 border-t border-white/20 pt-5"><div><span className="label text-white/40">ROLE</span><p className="mt-2">Strategy + Design</p></div><div><span className="label text-white/40">STACK</span><p className="mt-2">Next / GSAP / AI</p></div><div><span className="label text-white/40">YEAR</span><p className="mt-2">2026</p></div></div></div></div></motion.div>}</AnimatePresence></section>