'use client';
import {useRef,useState} from 'react';
import gsap from 'gsap';
import {ArrowUpRight} from 'lucide-react';
const articles=[
 {cat:'AI SYSTEMS',title:'Designing intelligence people can actually feel',date:'21.08.26',image:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=85'},
 {cat:'INTERACTION',title:'Why motion should behave like product logic',date:'14.08.26',image:'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1200&q=85'},
 {cat:'BRAND',title:'The new visual language of synthetic companies',date:'02.08.26',image:'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=85'},
 {cat:'STRATEGY',title:'Building digital products that sell the vision first',date:'27.07.26',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=85'}
];
export default function Insights(){const cursor=useRef<HTMLDivElement>(null);const [active,setActive]=useState<number|null>(null);function move(e:React.MouseEvent){if(!cursor.current)return;gsap.to(cursor.current,{x:e.clientX+24,y:e.clientY-100,duration:.55,ease:'power4.out'})}return <section id="insights" className="section-line relative px-5 py-24 md:px-8 md:py-36" onMouseMove={move}><div className="mx-auto max-w-[1600px]"><div className="mb-16 grid grid-cols-12 gap-6"><div className="col-span-12 md:col-span-4"><span className="label text-muted">INSIGHTS / 04</span></div><div className="col-span-12 md:col-span-8"><h2 className="display text-[15vw] font-medium md:text-[7vw]">THINKING<br/>IN <span className="italic font-normal">PUBLIC.</span></h2></div></div><div>{articles.map((a,i)=><article key={a.title} onMouseEnter={()=>{setActive(i);if(cursor.current)gsap.to(cursor.current,{scale:1,opacity:1,duration:.45,ease:'power4.out'})}} onMouseLeave={()=>{setActive(null);if(cursor.current)gsap.to(cursor.current,{scale:.7,opacity:0,duration:.35,ease:'power4.out'})}} className="group grid cursor-pointer grid-cols-12 items-center border-t border-black/20 py-6 last:border-b md:py-8"><span className="col-span-4 label text-muted md:col-span-2">{a.cat}</span><h3 className="col-span-8 text-2xl tracking-[-.04em] transition-transform duration-500 group-hover:translate-x-2 md:col-span-7 md:text-4xl">{a.title}</h3><span className="col-span-4 mt-4 label text-muted md:col-span-2 md:mt-0">{a.date}</span><ArrowUpRight className="col-span-1 ml-auto hidden transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1 md:block" size={20}/></article>)}</div></div><div ref={cursor} className="pointer-events-none fixed left-0 top-0 z-[70] hidden h-56 w-80 origin-center overflow-hidden bg-black opacity-0 md:block"><img src={active===null?articles[0].image:articles[active].image} alt="" className="h-full w-full object-cover grayscale"/><div className="absolute inset-0 halftone opacity-20"/></div></section>