'use client';
import Image from 'next/image';
import {MoveUpRight} from 'lucide-react';
import {MouseEvent,useRef,useState} from 'react';
import gsap from 'gsap';

type Insight={category:string;title:string;date:string;image:string};
const insights:Insight[]=[
 {category:'AI / CULTURE',title:'When machines develop taste',date:'18.08.26',image:'/softwarepar-portfolio/assets/insight-01.svg'},
 {category:'STRATEGY / GROWTH',title:'Designing momentum, not campaigns',date:'11.08.26',image:'/softwarepar-portfolio/assets/insight-02.svg'},
 {category:'PRODUCT / SYSTEMS',title:'Interfaces that think with you',date:'02.08.26',image:'/softwarepar-portfolio/assets/insight-03.svg'},
];
export default function Insights(){const cursor=useRef<HTMLDivElement>(null);const [image,setImage]=useState(insights[0].image);const move=(e:MouseEvent<HTMLDivElement>)=>{if(!cursor.current)return;gsap.to(cursor.current,{x:e.clientX+24,y:e.clientY-120,duration:.55,ease:'power4.out'})};const enter=(src:string)=>{setImage(src);if(cursor.current)gsap.to(cursor.current,{autoAlpha:1,scale:1,duration:.45,ease:'power4.out'})};const leave=()=>{if(cursor.current)gsap.to(cursor.current,{autoAlpha:0,scale:.82,duration:.35,ease:'power4.out'})};return <section id="insights" className="section-line px-5 py-28 md:px-8 md:py-40" onMouseMove={move}><div ref={cursor} className="pointer-events-none fixed left-0 top-0 z-[90] hidden h-[260px] w-[390px] overflow-hidden rounded-2xl opacity-0 shadow-2xl md:block"><Image src={image} alt="Insight preview" fill className="object-cover"/></div><div className="mx-auto max-w-[1600px]"><div className="mb-14 grid grid-cols-12 gap-6"><p className="label col-span-12 text-muted md:col-span-4">INSIGHTS / 04</p><h2 className="col-span-12 text-6xl font-medium tracking-[-.06em] md:col-span-8 md:text-8xl">Ideas for what comes next.</h2></div><div className="border-b border-border">{insights.map((item,i)=><div key={item.title} onMouseEnter={()=>enter(item.image)} onMouseLeave={leave} className="group grid cursor-pointer grid-cols-12 items-center gap-4 border-t border-border py-7 transition-colors duration-500 hover:bg-secondary md:py-9"><span className="label col-span-4 text-muted md:col-span-2">{item.category}</span><h3 className="col-span-8 text-2xl font-medium tracking-[-.035em] md:col-span-7 md:text-4xl">{item.title}</h3><span className="label col-span-8 col-start-5 text-muted md:col-span-2 md:col-start-auto">{item.date}</span><MoveUpRight className="col-span-4 justify-self-end transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1 md:col-span-1" size={20}/></div>)}</div></div></section>}
