'use client';
import {useState} from 'react';
import {motion,AnimatePresence} from 'framer-motion';
import {ArrowUpRight} from 'lucide-react';
const services=[
 {title:'AI Experiences',tag:'01',desc:'Interfaces and products where intelligence is part of the experience — not a decorative feature.',image:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=85'},
 {title:'Digital Products',tag:'02',desc:'High-value SaaS, dashboards and platforms engineered around clarity, speed and conversion.',image:'https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=1600&q=85'},
 {title:'Brand Systems',tag:'03',desc:'Identity systems with strong typographic language, motion rules and digital-first expression.',image:'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1600&q=85'},
 {title:'Interactive Web',tag:'04',desc:'Cinematic websites driven by scroll, spatial composition and purposeful microinteraction.',image:'https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=1600&q=85'}
];
export default function Services(){const [active,setActive]=useState(0);return <section id="expertise" className="section-line px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1600px]"><div className="mb-16 grid grid-cols-12 gap-4"><div className="col-span-12 md:col-span-5"><span className="label text-muted">OUR EXPERTISE / 01</span></div><div className="col-span-12 md:col-span-7"><h2 className="display max-w-4xl text-[14vw] font-medium md:text-[7vw]">WE DESIGN<br/>SYSTEMS THAT <span className="italic font-normal">MOVE.</span></h2></div></div><div className="grid grid-cols-12 gap-8 md:gap-12"><div className="col-span-12 md:col-span-5">{services.map((s,i)=><button key={s.title} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)} className="group flex w-full items-center justify-between border-t border-black/20 py-6 text-left last:border-b"><span className="flex items-baseline gap-4"><small className="label text-muted">{s.tag}</small><span className={`text-3xl tracking-[-.05em] transition-all duration-500 md:text-5xl ${active===i?'translate-x-2':'text-black/45'}`}>{s.title}</span></span><ArrowUpRight size={20} className={`transition-all duration-500 ${active===i?'rotate-45 opacity-100':'opacity-25'}`}/></button>)}</div><div className="col-span-12 md:col-span-7"><div className="sticky top-24 aspect-[4/3] overflow-hidden bg-black"><AnimatePresence mode="wait"><motion.div key={active} initial={{opacity:0,scale:1.04}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.98}} transition={{duration:.55,ease:[.22,1,.36,1]}} className="absolute inset-0"><img src={services[active].image} alt="" className="h-full w-full object-cover grayscale"/><div className="absolute inset-0 bg-black/20"/><div className="absolute bottom-0 left-0 right-0 flex items-end justify-between p-6 text-white md:p-8"><p className="max-w-md text-sm leading-6 md:text-base">{services[active].desc}</p><span className="label">0{active+1} / 04</span></div></motion.div></AnimatePresence></div></div></div></div></section>