'use client';

import {
  Activity, Bell, Bot, BrainCircuit, ChartNoAxesCombined, Check, ChevronRight,
  CircleDollarSign, Command, Database, FileClock, Gauge, HelpCircle, Menu,
  Moon, Play, Plus, Radar, Search, Settings, ShieldCheck, Sparkles,
  TerminalSquare, Users, Workflow, X, Zap, ZoomIn, ZoomOut, RotateCcw,
  PlugZap, UserCheck, Layers3, SunMedium, SlidersHorizontal, GitBranch,
  LockKeyhole, ArrowUpRight, Filter, Pause, RefreshCw, Network, CircleDot,
} from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import { useEffect, useMemo, useState } from 'react';

type IconType = typeof Activity;
type View = 'command'|'workflows'|'agents'|'automations'|'approvals'|'runtime'|'models'|'scenarios'|'analytics'|'governance'|'teams'|'audit'|'economics'|'integrations'|'settings';
type Tone = 'violet'|'blue'|'green'|'amber'|'pink'|'cyan';
type NavItem = { id:View; label:string; icon:IconType; group:string; badge?:string };
type Metric = { label:string; value:string; delta:string; tone:Tone; points:number[] };

type AgentRow = { name:string; role:string; runs:string; success:string; state:'Online'|'Paused'; tone:Tone };
type RuntimeRow = { time:string; actor:string; action:string; object:string; latency:string; status:'Success'|'Waiting'|'Info' };

type FlowNode = { id:string; title:string; subtitle:string; state:string; x:number; y:number; tone:Tone; icon:IconType };

const nav: NavItem[] = [
  {id:'command',label:'Command Center',icon:Radar,group:'HOME'},
  {id:'workflows',label:'Workflow Studio',icon:Workflow,group:'OPERATIONS'},
  {id:'agents',label:'Agent Fleet',icon:Bot,group:'OPERATIONS'},
  {id:'automations',label:'Automations',icon:Zap,group:'OPERATIONS'},
  {id:'approvals',label:'Human Review',icon:UserCheck,group:'OPERATIONS',badge:'3'},
  {id:'runtime',label:'Runtime Console',icon:TerminalSquare,group:'OPERATIONS'},
  {id:'models',label:'Model Router',icon:BrainCircuit,group:'INTELLIGENCE'},
  {id:'scenarios',label:'Scenarios',icon:Sparkles,group:'INTELLIGENCE'},
  {id:'analytics',label:'Analytics & Insights',icon:ChartNoAxesCombined,group:'INTELLIGENCE'},
  {id:'governance',label:'Governance',icon:ShieldCheck,group:'GOVERNANCE'},
  {id:'teams',label:'Teams & Access',icon:Users,group:'GOVERNANCE'},
  {id:'audit',label:'Audit Trail',icon:FileClock,group:'GOVERNANCE'},
  {id:'economics',label:'Economics',icon:CircleDollarSign,group:'BUSINESS'},
  {id:'integrations',label:'Integrations',icon:PlugZap,group:'BUSINESS'},
  {id:'settings',label:'Settings',icon:Settings,group:'SYSTEM'},
];

const metrics: Metric[] = [
  {label:'ACTIVE MISSIONS',value:'24',delta:'+18%',tone:'violet',points:[4,8,7,13,11,18,15,20,16,24]},
  {label:'SUCCESS RATE',value:'98.6%',delta:'+2.7%',tone:'blue',points:[7,10,9,15,13,17,15,21,19,24]},
  {label:'VALUE GENERATED',value:'$2.41M',delta:'+24%',tone:'green',points:[5,7,10,9,13,14,18,17,22,24]},
  {label:'COSTS',value:'$347K',delta:'-6%',tone:'amber',points:[5,9,8,12,11,15,13,18,17,22]},
  {label:'HUMAN HOURS SAVED',value:'2,846',delta:'+22%',tone:'pink',points:[5,6,10,9,14,12,18,16,21,23]},
];

const flowNodes: FlowNode[] = [
  {id:'ingest',title:'Data Ingestion',subtitle:'Completed',state:'completed',x:10,y:31,tone:'blue',icon:Database},
  {id:'score',title:'Lead Scoring',subtitle:'Completed',state:'completed',x:33,y:31,tone:'green',icon:BrainCircuit},
  {id:'outreach',title:'Outreach Agent',subtitle:'Running',state:'running',x:55,y:31,tone:'green',icon:Bot},
  {id:'review',title:'Human Review',subtitle:'Waiting',state:'waiting',x:78,y:31,tone:'amber',icon:UserCheck},
  {id:'enrich',title:'Enrichment',subtitle:'Completed',state:'completed',x:24,y:66,tone:'cyan',icon:Layers3},
  {id:'qualify',title:'Qualification',subtitle:'Completed',state:'completed',x:47,y:66,tone:'green',icon:ShieldCheck},
  {id:'create',title:'Create Opportunity',subtitle:'Pending',state:'pending',x:72,y:66,tone:'violet',icon:CircleDollarSign},
];

const agents: AgentRow[] = [
  {name:'Outreach Agent',role:'Revenue execution',runs:'1,247',success:'98.3%',state:'Online',tone:'violet'},
  {name:'Lead Scoring Agent',role:'Intent intelligence',runs:'882',success:'97.8%',state:'Online',tone:'green'},
  {name:'Research Agent',role:'Market context',runs:'675',success:'99.1%',state:'Online',tone:'cyan'},
  {name:'Enrichment Agent',role:'Data expansion',runs:'543',success:'98.6%',state:'Online',tone:'blue'},
  {name:'Finance Guard',role:'Budget authority',runs:'318',success:'99.4%',state:'Paused',tone:'amber'},
];

const runtimeRows: RuntimeRow[] = [
  {time:'12:45:32',actor:'Outreach Agent',action:'Email batch completed (143 sent)',object:'acme_corp_leads.csv',latency:'1.24s',status:'Success'},
  {time:'12:45:35',actor:'Human Review',action:'Approval requested (Budget: $12,450)',object:'opportunity_12345',latency:'—',status:'Waiting'},
  {time:'12:45:37',actor:'System',action:'Waiting for human decision...',object:'—',latency:'—',status:'Info'},
];

const toneHex: Record<Tone,string> = {
  violet:'#9b5cff',blue:'#16b3ff',green:'#28e47d',amber:'#ffb31f',pink:'#ff3f9d',cyan:'#10e2df'
};
const toneBg: Record<Tone,string> = {
  violet:'bg-violet-500/12 text-violet-300 border-violet-400/20',
  blue:'bg-sky-500/12 text-sky-300 border-sky-400/20',
  green:'bg-emerald-500/12 text-emerald-300 border-emerald-400/20',
  amber:'bg-amber-500/12 text-amber-300 border-amber-400/20',
  pink:'bg-pink-500/12 text-pink-300 border-pink-400/20',
  cyan:'bg-cyan-500/12 text-cyan-300 border-cyan-400/20',
};

const panel = 'rounded-[11px] border border-[#15233a] bg-[linear-gradient(180deg,rgba(5,13,26,.985),rgba(3,10,20,.99))] shadow-[0_12px_38px_rgba(0,0,0,.28)]';
const micro = 'text-[8px] font-medium tracking-[.08em] text-[#60708a]';

function Logo(){
  return <div className="flex items-center gap-2.5"><div className="relative grid size-8 place-items-center"><span className="absolute h-7 w-2 -rotate-[38deg] rounded-full bg-gradient-to-b from-cyan-300 via-violet-400 to-fuchsia-500 shadow-[0_0_16px_rgba(149,76,255,.55)]"/><span className="absolute h-7 w-2 rotate-[38deg] rounded-full bg-gradient-to-b from-violet-400 to-fuchsia-500 shadow-[0_0_16px_rgba(149,76,255,.35)]"/></div><div><p className="text-[13px] font-semibold tracking-[.16em] text-white">NEXORA</p><p className="text-[7px] tracking-[.14em] text-[#5c6475]">AI AUTONOMY OS</p></div></div>
}

function Sparkline({points,tone}:{points:number[];tone:Tone}){
  const max=Math.max(...points); const min=Math.min(...points); const d=points.map((p,i)=>`${i===0?'M':'L'} ${(i/(points.length-1))*72} ${26-((p-min)/(max-min||1))*22}`).join(' ');
  return <svg viewBox="0 0 72 28" className="h-7 w-[72px] overflow-visible"><path d={d} fill="none" stroke={toneHex[tone]} strokeWidth="1.5"/><path d={`${d} L72 28 L0 28 Z`} fill={toneHex[tone]} opacity=".08"/></svg>
}

function MetricCard({m}:{m:Metric}){
  return <motion.div whileHover={{y:-2,borderColor:'rgba(155,92,255,.28)'}} className={`${panel} min-w-0 px-3 py-2.5`}><div className="flex items-end justify-between gap-2"><div><p className={micro}>{m.label}</p><p className="mt-1.5 text-[21px] font-medium tracking-[-.04em] text-white">{m.value}</p><p className={`mt-0.5 text-[8px] font-semibold ${m.delta.startsWith('-')?'text-amber-400':'text-emerald-400'}`}>{m.delta.startsWith('-')?'↓':'↑'} {m.delta.replace('-','')}</p></div><Sparkline points={m.points} tone={m.tone}/></div></motion.div>
}

function HealthCard(){
  return <div className={`${panel} flex min-w-[190px] items-center justify-between px-3 py-2.5`}><div><p className={micro}>SYSTEM HEALTH</p><p className="mt-1.5 text-[13px] font-semibold text-emerald-300">Excellent</p><p className="mt-0.5 text-[8px] text-emerald-500">All systems operational</p></div><div className="relative grid size-[62px] place-items-center"><div className="absolute inset-0 rounded-full border border-cyan-400/20"/><div className="absolute inset-[6px] rounded-full border border-cyan-400/40 shadow-[0_0_18px_rgba(0,255,229,.12)]"/><div className="absolute inset-[12px] rounded-full border-2 border-emerald-400/70"/><span className="text-[12px] font-semibold text-cyan-200">100</span></div></div>
}

function HeaderButton({icon:Icon,badge,onClick}:{icon:IconType;badge?:string;onClick?:()=>void}){
  return <button onClick={onClick} className="relative grid size-9 place-items-center rounded-[9px] border border-[#142039] bg-[#07111f] text-[#8a97aa] transition hover:border-violet-400/30 hover:text-white"><Icon size={14}/>{badge&&<span className="absolute -right-1 -top-1 grid size-[17px] place-items-center rounded-full bg-violet-600 text-[7px] text-white">{badge}</span>}</button>
}

function MissionFlow({onToast}:{onToast:(s:string)=>void}){
  const[progress,setProgress]=useState(68); const[busy,setBusy]=useState(false); const[review,setReview]=useState(true);
  const run=()=>{if(busy)return;setBusy(true);setProgress(18);let p=18;const id=window.setInterval(()=>{p+=7;setProgress(p);if(p>=86){window.clearInterval(id);setBusy(false);setReview(true);onToast('Mission reached human authority gate')}},240)};
  const approve=()=>{setReview(false);setProgress(100);onToast('Human review approved · opportunity created')};
  return <div className={`${panel} overflow-hidden`}>
    <div className="flex items-start justify-between gap-3 border-b border-[#132138] px-4 py-3"><div><p className={micro}>MISSION FLOW</p><div className="mt-1 flex items-center gap-2"><h2 className="text-[15px] font-medium text-white">Q2 Revenue Acceleration</h2><span className="rounded-full border border-violet-400/20 bg-violet-500/10 px-2 py-[2px] text-[7px] text-violet-300">Enterprise</span></div><p className="mt-1 text-[8px] text-[#637087]">Increase qualified pipeline by 35% with AI-driven outbound & nurturing</p></div><div className="flex items-center gap-5"><div><p className={micro}>STATUS</p><p className="mt-1 text-[8px] text-emerald-400">● {busy?'Running':'Running'}</p></div><div><p className={micro}>PROGRESS</p><div className="mt-1 flex items-center gap-2"><div className="h-1 w-[86px] overflow-hidden rounded-full bg-[#101a2b]"><motion.div animate={{width:`${progress}%`}} className="h-full bg-gradient-to-r from-emerald-400 to-lime-400"/></div><span className="text-[8px] text-[#8f9bae]">{progress}%</span></div></div><div><p className={micro}>ELAPSED</p><p className="mt-1 text-[8px] text-[#a7b1c0]">00:24:18</p></div><button onClick={run} className="rounded-[7px] border border-emerald-400/15 bg-emerald-400/[0.05] px-2.5 py-1.5 text-[8px] text-emerald-300"><span className="mr-1 text-emerald-400">●</span>Live</button></div></div>
    <div className="relative h-[286px] overflow-hidden bg-[#04101f]">
      <div className="absolute inset-0 opacity-[.26] [background-image:radial-gradient(circle,rgba(76,118,165,.65)_1px,transparent_1px)] [background-size:6px_6px] [mask-image:radial-gradient(ellipse_at_center,black,transparent_72%)]"/>
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_52%_48%,rgba(27,255,114,.07),transparent_34%),radial-gradient(circle_at_72%_62%,rgba(159,74,255,.09),transparent_28%)]"/>
      <svg className="absolute inset-0 h-full w-full" viewBox="0 0 1000 286" preserveAspectRatio="none"><defs><linearGradient id="flowLine" x1="0" x2="1"><stop stopColor="#08a7ff"/><stop offset=".48" stopColor="#2ce47c"/><stop offset=".78" stopColor="#f0ad18"/><stop offset="1" stopColor="#9b5cff"/></linearGradient></defs><path d="M155 89 H320 M415 89 H515 M625 89 H760 M570 116 V188 H470 M370 116 V188 H270 M555 188 H720 V117" fill="none" stroke="url(#flowLine)" strokeWidth="2" strokeOpacity=".9" strokeDasharray="5 5"><animate attributeName="stroke-dashoffset" from="0" to="-22" dur="1.05s" repeatCount="indefinite"/></path></svg>
      {flowNodes.map(n=>{const Icon=n.icon;const isOut=n.id==='outreach';const subtitle=n.id==='review'?(review?'Waiting':'Completed'):n.id==='create'?(review?'Pending':'Completed'):n.subtitle;return <motion.div key={n.id} style={{left:`${n.x}%`,top:`${n.y}%`}} className="absolute -translate-x-1/2 -translate-y-1/2" animate={isOut&&busy?{filter:['drop-shadow(0 0 4px rgba(77,255,101,.25))','drop-shadow(0 0 14px rgba(77,255,101,.75))','drop-shadow(0 0 4px rgba(77,255,101,.25))']}:{}} transition={{repeat:Infinity,duration:1.4}}><div className={`min-w-[145px] rounded-[8px] border bg-[#061526]/95 px-2.5 py-2 shadow-[0_10px_26px_rgba(0,0,0,.34)] ${isOut?'border-lime-400/55 ring-1 ring-lime-400/20':'border-[#23405e]'}`}><div className="flex items-center gap-2"><div className={`grid size-7 place-items-center rounded-[6px] border ${toneBg[n.tone]}`}><Icon size={12}/></div><div><p className="text-[8px] font-medium text-white">{n.title}</p><p className={`mt-0.5 text-[7px] ${subtitle==='Waiting'?'text-amber-300':subtitle==='Pending'?'text-violet-300':'text-emerald-400'}`}>{subtitle}</p></div></div></div></motion.div>})}
      <div className="absolute bottom-3 left-3 flex gap-1.5"><button className="grid size-8 place-items-center rounded-[7px] border border-[#20324a] bg-[#06101e] text-[#748197]"><Plus size={12}/></button><button className="grid size-8 place-items-center rounded-[7px] border border-[#20324a] bg-[#06101e] text-[#748197]"><ZoomOut size={12}/></button><div className="grid min-w-12 place-items-center rounded-[7px] border border-[#20324a] bg-[#06101e] px-2 text-[7px] text-[#748197]">100%</div><button className="grid size-8 place-items-center rounded-[7px] border border-[#20324a] bg-[#06101e] text-[#748197]"><LockKeyhole size={11}/></button></div>
      <div className="absolute bottom-3 left-1/2 flex -translate-x-1/2 gap-3 rounded-full border border-[#1b2940] bg-[#071220]/90 px-3 py-1.5 text-[7px] text-[#8c98aa]"><span><b className="text-emerald-400">●</b> Completed</span><span><b className="text-lime-400">⊙</b> Running</span><span><b className="text-amber-400">●</b> Waiting</span><span><b className="text-rose-400">●</b> Blocked</span><span><b className="text-violet-400">●</b> Pending</span></div>
      {review&&<button onClick={approve} className="absolute bottom-3 right-3 rounded-[7px] border border-amber-400/20 bg-amber-400/10 px-3 py-1.5 text-[7px] text-amber-200">Approve human review</button>}
    </div>
  </div>
}

function ActivityFeed(){const rows=[['Outreach Agent sent 143 emails','',2,'violet'],['Human review requested','Budget approval for $12,450',4,'pink'],['Lead scored as High Intent','Acme Corp · Score: 92',6,'blue'],['Opportunity created','Acme Corp · $85,000',8,'amber'],['Data enrichment completed','245 new leads enriched',10,'green']] as const;return <div className={`${panel} p-3`}><div className="mb-1.5 flex items-center justify-between"><p className="text-[8px] font-semibold tracking-[.08em] text-[#8b98ab]">ACTIVITY FEED</p><button className="text-[7px] text-[#758096]">View all</button></div>{rows.map(([title,detail,time,t])=><div key={title} className="flex items-center gap-2 border-b border-[#111e31] py-2 last:border-0"><div className={`grid size-6 shrink-0 place-items-center rounded-[6px] border ${toneBg[t]}`}><Activity size={10}/></div><div className="min-w-0 flex-1"><p className="truncate text-[8px] text-[#d9e1ed]">{title}</p>{detail&&<p className="truncate text-[7px] text-[#59687d]">{detail}</p>}</div><span className="text-[7px] text-[#667287]">{time}m ago</span><span className="size-1 rounded-full bg-emerald-400"/></div>)}</div>}

function SystemMap(){const nodes=[['LLM Services','99.9%',50,10,'green'],['Vector DB','99.8%',84,19,'cyan'],['Memory Store','99.9%',86,69,'green'],['Tool Execution','99.7%',52,84,'cyan'],['Data Pipeline','99.9%',16,63,'cyan']] as const;return <div className={`${panel} p-3`}><p className="text-[8px] font-semibold tracking-[.08em] text-[#8b98ab]">REAL-TIME SYSTEM MAP</p><div className="relative mt-1 h-[152px] overflow-hidden rounded-[8px] bg-[radial-gradient(circle_at_center,rgba(122,55,255,.13),transparent_52%)]"><div className="absolute left-1/2 top-1/2 size-[118px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-violet-500/20"/><div className="absolute left-1/2 top-1/2 size-[170px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-sky-400/16"/><div className="absolute left-1/2 top-1/2 grid size-[58px] -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border border-violet-400/35 bg-violet-500/12 shadow-[0_0_30px_rgba(137,73,255,.24)]"><div className="text-center"><Sparkles size={13} className="mx-auto text-violet-300"/><p className="mt-1 text-[7px] text-violet-200">NEXORA CORE</p></div></div>{nodes.map(([label,val,l,t,c])=><div key={label} style={{left:`${l}%`,top:`${t}%`}} className="absolute -translate-x-1/2 -translate-y-1/2 text-center"><div className={`mx-auto grid size-6 place-items-center rounded-full border ${toneBg[c]}`}><CircleDot size={10}/></div><p className="mt-0.5 whitespace-nowrap text-[7px] text-[#c8d2df]">{label}</p><p className="text-[7px] text-emerald-400">{val}</p></div>)}</div></div>}

function Scenarios(){const rows=[['Q2 Revenue Acceleration','Running','violet'],['Risk Mitigation & Compliance','Ready','blue'],['Customer Onboarding 2.0','Ready','green'],['Operational Efficiency','Draft','amber']] as const;return <div className={`${panel} p-3`}><div className="mb-2 flex justify-between"><p className="text-[8px] font-semibold tracking-[.08em] text-[#8b98ab]">SCENARIOS</p><span className="text-[7px] text-[#67758b]">View all</span></div>{rows.map(([name,state,t],i)=><button key={name} className={`mb-1.5 flex w-full items-center gap-2 rounded-[8px] border px-2.5 py-2 text-left ${i===0?'border-violet-500/28 bg-violet-500/[0.07]':'border-[#16243a] bg-[#07121f]'}`}><div className={`grid size-6 place-items-center rounded-[6px] border ${toneBg[t]}`}><Sparkles size={10}/></div><span className="min-w-0 flex-1 truncate text-[8px] text-[#d5deea]">{name}</span><span className={`rounded px-1.5 py-[2px] text-[7px] ${state==='Draft'?'bg-amber-500/12 text-amber-300':'bg-emerald-500/12 text-emerald-300'}`}>{state}</span></button>)}</div>}

function ValueChart(){return <div className={`${panel} p-3`}><div className="flex items-start justify-between"><div><p className="text-[8px] font-semibold tracking-[.08em] text-[#8b98ab]">VALUE OVER TIME</p><p className="mt-2 text-[20px] font-medium text-white">$2.41M <span className="text-[8px] text-emerald-400">↑18% <span className="text-[#59687d]">vs last 30 days</span></span></p></div><div className="flex gap-1 text-[7px] text-[#657187]"><span>7D</span><span className="rounded bg-violet-500/15 px-1.5 py-[2px] text-violet-300">30D</span><span>90D</span><span>1Y</span></div></div><svg viewBox="0 0 360 118" className="mt-1 h-[118px] w-full"><defs><linearGradient id="areaV11" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#9b5cff" stopOpacity=".38"/><stop offset="1" stopColor="#9b5cff" stopOpacity="0"/></linearGradient></defs><path d="M0 98 C22 95 21 77 42 82 S70 87 87 65 S121 82 141 60 S177 66 198 43 S231 60 251 39 S286 57 306 30 S333 39 360 15 L360 118 L0 118Z" fill="url(#areaV11)"/><path d="M0 98 C22 95 21 77 42 82 S70 87 87 65 S121 82 141 60 S177 66 198 43 S231 60 251 39 S286 57 306 30 S333 39 360 15" fill="none" stroke="#a970ff" strokeWidth="1.5"/><g fill="#68758a" fontSize="7"><text x="2" y="116">Apr 22</text><text x="75" y="116">Apr 29</text><text x="148" y="116">May 6</text><text x="221" y="116">May 13</text><text x="314" y="116">May 20</text></g></svg></div>}

function TopAgents(){return <div className={`${panel} p-3`}><div className="mb-1 flex justify-between"><p className="text-[8px] font-semibold tracking-[.08em] text-[#8b98ab]">TOP AGENTS</p><span className="text-[7px] text-[#67758b]">View all</span></div>{agents.slice(0,4).map(a=><div key={a.name} className="flex items-center gap-2 border-b border-[#111e31] py-1.5 last:border-0"><div className={`grid size-6 place-items-center rounded-full border ${toneBg[a.tone]}`}><Bot size={10}/></div><div className="min-w-0 flex-1"><p className="truncate text-[8px] text-[#dce4ee]">{a.name}</p><p className="text-[7px] text-[#59687d]">{a.runs} runs</p></div><Sparkline points={[5,7,9,8,13,11,15,18]} tone={a.tone}/><span className="w-9 text-right text-[8px] text-[#cdd7e4]">{a.success}</span></div>)}</div>}

function QuickActions({onAction}:{onAction:(s:string)=>void}){const items:[string,IconType,Tone][]=[['New Workflow',Plus,'violet'],['Deploy Agent',Bot,'violet'],['Create Scenario',Sparkles,'amber'],['Run Simulation',Play,'blue']];return <div className={`${panel} p-3`}><p className="text-[8px] font-semibold tracking-[.08em] text-[#8b98ab]">QUICK ACTIONS</p><div className="mt-2 grid grid-cols-2 gap-2">{items.map(([label,Icon,t])=><motion.button whileHover={{y:-1,scale:1.01}} key={label} onClick={()=>onAction(label)} className={`flex min-h-[50px] items-center gap-2 rounded-[8px] border px-2.5 text-left ${toneBg[t]}`}><div className="grid size-7 place-items-center rounded-full bg-black/10"><Icon size={12}/></div><span className="text-[8px] text-[#d9e2ee]">{label}</span></motion.button>)}</div></div>}

function RuntimeConsole(){return <div className={`${panel} overflow-hidden`}><div className="flex items-center justify-between border-b border-[#142138] px-3 py-2"><div className="flex items-center gap-2"><TerminalSquare size={12} className="text-[#8190a7]"/><span className="text-[8px] font-semibold tracking-[.08em] text-[#8b98ab]">RUNTIME CONSOLE</span></div><div className="flex items-center gap-2"><div className="flex items-center gap-1 rounded-[7px] border border-[#1c2b42] bg-[#07111f] px-2 py-1 text-[7px] text-[#647188]"><Filter size={9}/> Filter logs...</div><span className="text-[7px] text-[#67758b]">Auto-scroll</span><span className="h-4 w-7 rounded-full bg-emerald-400/20 p-[2px]"><span className="block size-3 translate-x-3 rounded-full bg-emerald-400"/></span><button className="ml-2 rounded-[7px] border border-[#223149] bg-[#0a1524] px-2.5 py-1.5 text-[7px] text-[#a6b1c1]">Open Console</button></div></div><div className="grid grid-cols-[74px_120px_1fr_130px_64px_76px] gap-x-3 px-3 py-2 font-mono text-[7px]">{runtimeRows.map(r=><div key={r.time} className="contents"><span className="py-1 text-[#5d6a80]">{r.time}</span><span className="py-1 text-sky-300">{r.actor}</span><span className="py-1 text-[#8f9bae]">{r.action}</span><span className="truncate py-1 text-[#637087]">{r.object}</span><span className="py-1 text-[#637087]">{r.latency}</span><span className={`py-1 ${r.status==='Success'?'text-emerald-400':r.status==='Waiting'?'text-amber-400':'text-sky-400'}`}>● {r.status}</span></div>)}</div></div>}

function CommandCenter({onToast}:{onToast:(s:string)=>void}){
  return <div className="space-y-3"><div className="grid grid-cols-2 gap-2 md:grid-cols-3 xl:grid-cols-[repeat(5,minmax(0,1fr))_190px]">{metrics.map(m=><MetricCard key={m.label} m={m}/>)}<HealthCard/></div><div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_276px]"><MissionFlow onToast={onToast}/><div className="grid gap-3"><ActivityFeed/><SystemMap/></div></div><div className="grid gap-3 xl:grid-cols-[.95fr_1.2fr_.92fr_.95fr]"><Scenarios/><ValueChart/><TopAgents/><QuickActions onAction={onToast}/></div><RuntimeConsole/></div>
}

function SectionHeader({view,title,subtitle,onAction}:{view:View;title:string;subtitle:string;onAction:(s:string)=>void}){return <div className="mb-3 flex items-end justify-between"><div><p className="text-[8px] uppercase tracking-[.14em] text-violet-300">NEXORA / {view}</p><h1 className="mt-1.5 text-[22px] font-medium tracking-[-.03em] text-white">{title}</h1><p className="mt-1 text-[9px] text-[#647188]">{subtitle}</p></div><button onClick={()=>onAction(`New ${title} action`)} className="flex items-center gap-1.5 rounded-[8px] border border-violet-400/20 bg-violet-500/10 px-3 py-2 text-[8px] text-violet-200"><Plus size={11}/> New action</button></div>}

function DataTable({columns,rows}:{columns:string[];rows:string[][]}){return <div className={`${panel} overflow-hidden`}><div className="grid gap-3 border-b border-[#142138] bg-[#06101f] px-3 py-2 text-[7px] uppercase tracking-[.08em] text-[#617088]" style={{gridTemplateColumns:`repeat(${columns.length},minmax(0,1fr))`}}>{columns.map(c=><span key={c}>{c}</span>)}</div>{rows.map((r,i)=><div key={i} className="grid gap-3 border-b border-[#101c2e] px-3 py-2.5 text-[8px] text-[#aeb9c8] last:border-0 hover:bg-white/[0.015]" style={{gridTemplateColumns:`repeat(${columns.length},minmax(0,1fr))`}}>{r.map((c,j)=><span key={j} className={j===r.length-1&&/Online|Success|Active|Ready/.test(c)?'text-emerald-400':''}>{c}</span>)}</div>)}</div>}

function ModuleView({view,onAction}:{view:View;onAction:(s:string)=>void}){
  const names:Record<View,[string,string]>={command:['Command Center',''],workflows:['Workflow Studio','Design, validate and run autonomous workflows.'],agents:['Agent Fleet','Monitor agent performance, state and operational ownership.'],automations:['Automations','Schedule and control recurring autonomous work.'],approvals:['Human Review','Resolve gated actions that require accountable approval.'],runtime:['Runtime Console','Inspect live events, traces, latency and execution outcomes.'],models:['Model Router','Route tasks across models by cost, latency and quality.'],scenarios:['Scenarios','Package business outcomes into reusable autonomous playbooks.'],analytics:['Analytics & Insights','Measure value, efficiency, quality and business impact.'],governance:['Governance','Control autonomy, risk, authority and compliance boundaries.'],teams:['Teams & Access','Manage operators, roles and delegated authority.'],audit:['Audit Trail','Trace every decision, tool call, approval and outcome.'],economics:['Economics','Track spend, generated value and unit economics.'],integrations:['Integrations','Connect NEXORA to enterprise systems and data.'],settings:['Settings','Configure workspace defaults, alerts and runtime behavior.']};
  const [title,subtitle]=names[view];
  if(view==='agents') return <><SectionHeader view={view} title={title} subtitle={subtitle} onAction={onAction}/><div className="grid gap-3 xl:grid-cols-[1.5fr_.7fr]"><DataTable columns={['Agent','Role','Runs','Success','State']} rows={agents.map(a=>[a.name,a.role,a.runs,a.success,a.state])}/><div className={`${panel} p-3`}><p className={micro}>FLEET HEALTH</p><div className="mt-3 grid place-items-center"><div className="relative grid size-36 place-items-center rounded-full border border-violet-400/20"><div className="absolute inset-3 rounded-full border border-cyan-400/20"/><div className="absolute inset-7 rounded-full border-2 border-emerald-400/60"/><div className="text-center"><p className="text-3xl font-medium text-white">97.9</p><p className="text-[8px] text-emerald-400">Fleet score</p></div></div></div></div></div></>;
  if(view==='runtime') return <><SectionHeader view={view} title={title} subtitle={subtitle} onAction={onAction}/><RuntimeConsole/><div className="mt-3 grid gap-3 xl:grid-cols-3">{['Event throughput','P95 latency','Tool failures'].map((x,i)=><div key={x} className={`${panel} p-3`}><p className={micro}>{x.toUpperCase()}</p><p className="mt-2 text-2xl text-white">{i===0?'128/s':i===1?'1.42s':'0.17%'}</p><Sparkline points={[4,7,6,11,10,14,13,16,20]} tone={i===2?'amber':'cyan'}/></div>)}</div></>;
  if(view==='governance') return <><SectionHeader view={view} title={title} subtitle={subtitle} onAction={onAction}/><div className="grid gap-3 xl:grid-cols-[1.15fr_.85fr]"><div className={`${panel} p-3`}><p className={micro}>AUTHORITY MATRIX</p><DataTable columns={['Domain','Autonomy','Approval','Owner']} rows={[["Revenue outreach","High","$10K+","RevOps"],["Pricing changes","Medium","Required","Finance"],["Data deletion","Low","Always","Security"],["Customer comms","High","Risk-based","CX Ops"]]}/></div><div className={`${panel} p-3`}><p className={micro}>POLICY CONTROLS</p><div className="mt-2 space-y-2">{['Human authority gates','Economic guardrails','PII protection','Regional compliance'].map((x,i)=><button key={x} onClick={()=>onAction(`${x} toggled`)} className="flex w-full items-center justify-between rounded-[8px] border border-[#18273d] bg-[#07121f] px-3 py-2"><div className="text-left"><p className="text-[8px] text-[#d7e0eb]">{x}</p><p className="text-[7px] text-[#5f6d82]">Policy active</p></div><span className={`relative h-5 w-9 rounded-full border ${i===3?'border-amber-400/20 bg-amber-400/10':'border-cyan-400/20 bg-cyan-400/10'}`}><span className={`absolute top-[2px] size-[14px] rounded-full ${i===3?'left-[2px] bg-amber-300':'right-[2px] bg-cyan-300 shadow-[0_0_10px_rgba(34,211,238,.45)]'}`}/></span></button>)}</div></div></div></>;
  return <><SectionHeader view={view} title={title} subtitle={subtitle} onAction={onAction}/><div className="grid gap-3 xl:grid-cols-[1.4fr_.8fr]"><div className={`${panel} min-h-[440px] p-3`}><div className="flex items-center justify-between"><p className={micro}>LIVE OPERATIONAL SURFACE</p><div className="flex gap-1"><button className="grid size-7 place-items-center rounded-[6px] border border-[#1b2940] text-[#748197]"><RefreshCw size={10}/></button><button className="grid size-7 place-items-center rounded-[6px] border border-[#1b2940] text-[#748197]"><SlidersHorizontal size={10}/></button></div></div><div className="mt-3 grid h-[380px] place-items-center rounded-[8px] border border-[#15243a] bg-[radial-gradient(circle_at_center,rgba(111,59,255,.10),transparent_48%)]"><div className="text-center"><div className="mx-auto grid size-20 place-items-center rounded-full border border-violet-400/30 bg-violet-500/10 shadow-[0_0_40px_rgba(124,58,237,.15)]"><Network size={26} className="text-violet-300"/></div><p className="mt-4 text-[12px] text-[#dbe3ed]">{title} live workspace</p><p className="mt-1 text-[8px] text-[#617088]">Select an object or execute an action to inspect telemetry.</p></div></div></div><div className="space-y-3"><div className={`${panel} p-3`}><p className={micro}>STATUS</p><div className="mt-3 space-y-2">{['Runtime','Policy coverage','Data freshness','Human authority'].map((x,i)=><div key={x} className="flex justify-between border-b border-[#111e31] pb-2 text-[8px] last:border-0"><span className="text-[#748197]">{x}</span><span className={i===1?'text-amber-300':'text-emerald-400'}>{i===1?'94.2%':'Operational'}</span></div>)}</div></div><div className={`${panel} p-3`}><p className={micro}>RECENT EVENTS</p>{runtimeRows.map(r=><div key={r.time} className="mt-2 border-l border-violet-400/20 pl-2"><p className="text-[8px] text-[#c8d2df]">{r.action}</p><p className="text-[7px] text-[#59687d]">{r.time} · {r.actor}</p></div>)}</div></div></div></>
}

export default function NexoraV11(){
  const[view,setView]=useState<View>('command'); const[mobile,setMobile]=useState(false); const[palette,setPalette]=useState(false); const[notifications,setNotifications]=useState(false); const[toast,setToast]=useState(''); const[query,setQuery]=useState('');
  const groups=useMemo(()=>Array.from(new Set(nav.map(n=>n.group))),[]); const flash=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(''),1800)};
  useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(v=>!v)}if(e.key==='Escape'){setPalette(false);setNotifications(false);setMobile(false)}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[]);
  const choose=(id:View)=>{setView(id);setMobile(false);setPalette(false)};
  return <main className="min-h-screen bg-[#02060e] font-sans text-[#e7edf6] selection:bg-violet-500 selection:text-white"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_76%_-15%,rgba(70,31,163,.16),transparent_25%),radial-gradient(circle_at_20%_25%,rgba(0,149,255,.045),transparent_24%)]"/>
    <div className="relative mx-auto flex min-h-screen max-w-[1480px] border-x border-[#101a2b] bg-[#020711] shadow-[0_0_120px_rgba(0,0,0,.45)]">
      <aside className="sticky top-0 hidden h-screen w-[222px] shrink-0 border-r border-[#111c2d] bg-[#030914] px-3 py-4 lg:flex lg:flex-col"><Logo/><div className="mt-5 flex-1 overflow-y-auto pr-1">{groups.map(g=><div key={g} className="mb-3.5"><p className="mb-1.5 px-2 text-[7px] tracking-[.11em] text-[#4e5a6d]">{g==='HOME'?'':g}</p>{nav.filter(n=>n.group===g).map(({id,label,icon:Icon,badge})=><button key={id} onClick={()=>choose(id)} className={`mb-1 flex w-full items-center gap-2.5 rounded-[8px] border px-2.5 py-2 text-left text-[8px] transition ${view===id?'border-violet-500/25 bg-[linear-gradient(90deg,rgba(109,40,217,.24),rgba(76,29,149,.08))] text-white shadow-[inset_2px_0_0_#a855f7,0_0_18px_rgba(124,58,237,.08)]':'border-transparent text-[#8190a4] hover:border-[#17253b] hover:bg-[#07111f] hover:text-white'}`}><Icon size={12}/><span className="flex-1">{label}</span>{badge&&<span className="grid min-w-4 place-items-center rounded-full bg-violet-600/60 px-1 py-[1px] text-[7px] text-white">{badge}</span>}{view===id&&<ChevronRight size={9} className="text-violet-300"/>}</button>)}</div>)}</div><div className="mb-2 space-y-1"><button onClick={()=>choose('settings')} className="flex w-full items-center gap-2 rounded-[8px] px-2.5 py-2 text-[8px] text-[#8190a4] hover:bg-[#07111f]"><Settings size={12}/>Settings</button><button onClick={()=>setPalette(true)} className="flex w-full items-center gap-2 rounded-[8px] px-2.5 py-2 text-[8px] text-[#8190a4] hover:bg-[#07111f]"><Command size={12}/>Command Palette<span className="ml-auto rounded border border-[#26364f] px-1 py-[1px] text-[6px]">⌘K</span></button></div><div className="rounded-[9px] border border-[#18263b] bg-[#06101d] p-2.5"><div className="flex items-center gap-2"><div className="grid size-7 place-items-center rounded-full border border-violet-400/20 bg-violet-500/10 text-[8px] text-violet-200">PS</div><div className="min-w-0"><p className="truncate text-[8px] text-[#e4eaf3]">Pablo Solla</p><p className="text-[7px] text-[#59687d]">Enterprise Plan</p></div><ChevronRight size={9} className="ml-auto text-[#536176]"/></div></div></aside>
      <section className="min-w-0 flex-1"><header className="sticky top-0 z-40 border-b border-[#101c2d] bg-[#020711]/92 px-3 py-2.5 backdrop-blur-xl md:px-4"><div className="flex items-center gap-2"><button onClick={()=>setMobile(true)} className="grid size-9 place-items-center rounded-[8px] border border-[#17243a] text-[#8995a8] lg:hidden"><Menu size={14}/></button><div className="hidden flex-1 md:block"><p className="text-[13px] font-medium text-white">Good morning, Pablo 👋</p><p className="mt-0.5 text-[7px] text-[#657187]">Here’s what’s happening across your autonomous operations</p></div><button onClick={()=>setPalette(true)} className="ml-auto flex h-9 w-full max-w-[290px] items-center gap-2 rounded-[8px] border border-violet-500/28 bg-violet-500/[0.07] px-3 text-[7px] text-[#7b879b] shadow-[inset_0_0_20px_rgba(124,58,237,.03)]"><Command size={11}/><span className="flex-1 text-left">⌘K to search or run a command</span><span className="rounded-[5px] border border-violet-500/25 bg-violet-500/10 px-1.5 py-[2px] text-[6px] text-violet-300">⌘K</span></button><HeaderButton icon={Activity}/><HeaderButton icon={Bell} badge="7" onClick={()=>setNotifications(v=>!v)}/><HeaderButton icon={HelpCircle}/><HeaderButton icon={SunMedium}/><div className="ml-1 grid size-8 place-items-center rounded-full border border-[#2b3a50] bg-gradient-to-br from-[#d8d2c0] to-[#67594a] text-[7px] font-semibold text-black">PS</div></div></header>
        <div className="p-3 md:p-4">{view==='command'?<CommandCenter onToast={flash}/>:<ModuleView view={view} onAction={flash}/>}</div>
      </section>
    </div>
    <AnimatePresence>{mobile&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-[#020711]/96 p-4 backdrop-blur-2xl lg:hidden"><div className="flex items-center justify-between"><Logo/><button onClick={()=>setMobile(false)} className="grid size-9 place-items-center rounded-[8px] border border-[#1a293f]"><X size={14}/></button></div><div className="mt-5 grid gap-1">{nav.map(({id,label,icon:Icon})=><button key={id} onClick={()=>choose(id)} className="flex items-center gap-3 rounded-[8px] border border-[#15243a] bg-[#06101d] px-3 py-2.5 text-left text-[11px]"><Icon size={14}/>{label}</button>)}</div></motion.div>}</AnimatePresence>
    <AnimatePresence>{palette&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setPalette(false)} className="fixed inset-0 z-[70] grid place-items-start bg-black/70 px-4 pt-[10vh] backdrop-blur-sm"><motion.div initial={{y:-10,scale:.98}} animate={{y:0,scale:1}} onClick={e=>e.stopPropagation()} className="w-full max-w-xl rounded-[12px] border border-violet-500/25 bg-[#06101d] p-2 shadow-[0_30px_100px_rgba(0,0,0,.65)]"><div className="flex items-center gap-2 rounded-[8px] border border-[#1b2940] bg-[#030a14] px-3"><Search size={12}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search modules, agents or actions…" className="h-10 flex-1 bg-transparent text-[10px] outline-none"/></div><div className="mt-1 max-h-72 overflow-auto">{nav.filter(n=>n.label.toLowerCase().includes(query.toLowerCase())).map(({id,label,icon:Icon})=><button key={id} onClick={()=>choose(id)} className="flex w-full items-center gap-2 rounded-[7px] px-3 py-2.5 text-left text-[9px] hover:bg-white/[0.03]"><Icon size={12} className="text-violet-300"/>{label}<ChevronRight size={10} className="ml-auto text-[#536176]"/></button>)}</div></motion.div></motion.div>}</AnimatePresence>
    <AnimatePresence>{notifications&&<motion.div initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} className="fixed right-5 top-[58px] z-[65] w-[310px] rounded-[11px] border border-[#1a293f] bg-[#06101d] p-3 shadow-2xl"><div className="flex justify-between"><p className="text-[10px] font-semibold">Notifications</p><button onClick={()=>setNotifications(false)}><X size={12}/></button></div><div className="mt-2 space-y-1.5">{runtimeRows.map(r=><div key={r.time} className="rounded-[8px] border border-[#15243a] bg-[#040d18] p-2.5"><p className="text-[8px] text-[#d4deea]">{r.action}</p><p className="mt-0.5 text-[7px] text-[#59687d]">{r.time} · {r.actor}</p></div>)}</div></motion.div>}</AnimatePresence>
    <AnimatePresence>{toast&&<motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} exit={{opacity:0,y:16}} className="fixed bottom-5 left-1/2 z-[80] -translate-x-1/2 rounded-[8px] border border-emerald-400/20 bg-[#071712] px-3 py-2 text-[8px] text-emerald-200 shadow-2xl"><Check size={10} className="mr-1.5 inline"/>{toast}</motion.div>}</AnimatePresence>
  </main>
}
